name: Lock Issue And Delete Comment

on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

jobs:
  lock-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: lock issue and delete comment
        uses: ./
        with:
          test-regex: ${{ secrets.REGEX_ISSUE_INTERCEPTOR }}
          token: ${{ secrets.GITHUB_TOKEN }}
          title-override: 'xxx'
          body-override: 'xxx'
          lock-reason: 'spam'
